### ISSUE TITLE
How to access the values in extension 

### ISSUE THREAD

**Issue by Faisalkc4u** [patrick-fu/flutter_shared_preference_app_group#3]

**Comment by patrick-fu** [comment]
https://github.com/zegoim/zego-express-example-screen-capture-flutter

Here's an example demo implements screen live broadcast on iOS/Android, which using this "shared_preferences_app_group" plug-in.

And you can refer to [this code](https://github.com/zegoim/zego-express-example-screen-capture-flutter/blob/552996e9e45fce6f771835fe9ccf40c1efb0ba99/ios/BroadcastExtensionFlutter/ZGScreenCaptureManager.m#L187) which access the values in broadcast upload extension.

**Comment by Faisalkc4u** [comment]
@patrick-fu  
When I run this example project 
In Xcode I cannot find any group information
It was empty
Do I need the keep Like empty group ?

<img width="696" alt="Screen Shot 2021-04-01 at 11 52 32 AM" src="https://user-images.githubusercontent.com/12441355/113261920-16a2d880-92e1-11eb-87fa-1b5a620aec33.png">

**Comment by patrick-fu** [comment]
@Faisalkc4u You need to click the "+" button to add(or create) an "App Groups" yourself, because app groups are included in each developer account (Team ID)
